name: Deploy Prod

env:
    DOCKER_IMAGE_BACK: mustai-back
    DOCKER_IMAGE_FRONT: mustai-front
    MONGODB_URI: mongodb://mustai-mongo:27017
    OPEN_AI_SECRET: ${{ secrets.OPEN_AI_SECRET }}
    OPEN_AI_COMPLETION_URL: ${{ vars.OPEN_AI_COMPLETION_URL }}
    TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
    API_URL: ${{ vars.API_URL }}
on:
    # Runs on pushes targeting the default branch
    push:
        branches: [ "main" ]
        tags: [ 'v*' ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

# Allow one concurrent deployment
concurrency:
    group: "pages"
    cancel-in-progress: true

jobs:
    build-front:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Create env file
                run: |
                    cd app/frontend
                    touch .env
                    echo OPEN_AI_COMPLETION_URL=${{ vars.OPEN_AI_COMPLETION_URL }} >> .env
                    echo API_URL=${{ vars.API_URL }} >> .env
                    cat .env

            -   name: Build and save Docker images
                run: |
                    docker build --tag $DOCKER_IMAGE_FRONT --file build/docker/front.build.dockerfile .
                    docker save $DOCKER_IMAGE_FRONT > $DOCKER_IMAGE_FRONT.tar

            -   name: Upload artifacts
                uses: actions/upload-artifact@v3
                with:
                    name: my-artifacts
                    path: ${{env.DOCKER_IMAGE_FRONT}}.tar

    build-back:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Build and save Docker images
                run: |
                    docker build \
                    --tag $DOCKER_IMAGE_BACK \
                    --file build/docker/back.build.dockerfile \
                    --build-arg MONGODB_URI=${{MONGODB_URI}} \
                    --build-arg OPEN_AI_SECRET=${{OPEN_AI_SECRET}} \
                    --build-arg TMDB_API_KEY=${{TMDB_API_KEY}} .
                    docker save $DOCKER_IMAGE_BACK > $DOCKER_IMAGE_BACK.tar


            -   name: Upload artifacts
                uses: actions/upload-artifact@v3
                with:
                    name: my-artifacts
                    path: ${{env.DOCKER_IMAGE_BACK}}.tar

    send-front-to-server:
        needs: [ build-front ]
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Download artifacts
                uses: actions/download-artifact@v3
                with:
                    name: my-artifacts
                    path: artifacts

            -   name: Copy front artifact to server
                uses: burnett01/rsync-deployments@5.2.1
                with:
                    switches: -avzr --update --ignore-existing
                    path: ./artifacts/${{env.DOCKER_IMAGE_FRONT}}.tar
                    remote_path: /home/${{ secrets.VPS_USERNAME }}/app/
                    remote_host: ${{ secrets.VPS_HOST }}
                    remote_port: ${{ secrets.VPS_PORT }}
                    remote_user: ${{ secrets.VPS_USERNAME }}
                    remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

    send-back-to-server:
        needs: [ build-back ]
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Download artifacts
                uses: actions/download-artifact@v3
                with:
                    name: my-artifacts
                    path: artifacts

            -   name: Copy back artifact to server
                uses: burnett01/rsync-deployments@5.2.1
                with:
                    switches: -avzr --update --ignore-existing
                    path: ./artifacts/${{env.DOCKER_IMAGE_BACK}}.tar
                    remote_path: /home/${{ secrets.VPS_USERNAME }}/app/
                    remote_host: ${{ secrets.VPS_HOST }}
                    remote_port: ${{ secrets.VPS_PORT }}
                    remote_user: ${{ secrets.VPS_USERNAME }}
                    remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

    deploy:
        needs: [ send-back-to-server, send-front-to-server ]
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Copy docker-compose.dev.yml to server
                uses: burnett01/rsync-deployments@5.2.1
                with:
                    switches: -avzr --update --ignore-existing
                    path: ./build/docker-compose.prod.yml
                    remote_path: /home/${{ secrets.VPS_USERNAME }}/app/
                    remote_host: ${{ secrets.VPS_HOST }}
                    remote_port: ${{ secrets.VPS_PORT }}
                    remote_user: ${{ secrets.VPS_USERNAME }}
                    remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

            -   name: Compile and deploy
                env:
                    DOCKER_IMAGE_FRONT: ${{ env.DOCKER_IMAGE_FRONT }}
                    DOCKER_IMAGE_BACK: ${{ env.DOCKER_IMAGE_BACK }}
                uses: appleboy/ssh-action@master
                with:
                    host: ${{ secrets.VPS_HOST }}
                    username: ${{ secrets.VPS_USERNAME }}
                    password: ${{ secrets.VPS_PASSWORD }}
                    port: ${{ secrets.VPS_PORT }}
                    timeout: 300s
                    script: |
                        cd /home/${{ secrets.VPS_USERNAME }}/app
                        export DOCKER_IMAGE_FRONT=${{ env.DOCKER_IMAGE_FRONT }}
                        export DOCKER_IMAGE_BACK=${{ env.DOCKER_IMAGE_BACK }}
                        docker compose -f docker-compose.prod.yml down
                        docker load -i ${{ env.DOCKER_IMAGE_FRONT }}.tar
                        docker load -i ${{ env.DOCKER_IMAGE_BACK }}.tar
                        docker compose -f docker-compose.prod.yml up -d
