name: Deploy

env:
    DOCKER_IMAGE_BACK: mustai-back
    DOCKER_IMAGE_FRONT: mustai-front
    OPEN_AI_SECRET: ${{ secrets.OPEN_AI_SECRET }}
    OPEN_AI_COMPLETION_URL: ${{ vars.OPEN_AI_COMPLETION_URL }}
    TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
    API_URL: ${{ vars.API_URL }}

on:
    # Runs on pushes targeting the default branch
    push:
        branches: [ "main" ]
        tags: [ 'v*' ]

    pull_request:
        branches: [ "main" ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

# Allow one concurrent deployment
concurrency:
    group: "pages"
    cancel-in-progress: true

jobs:
    build-front:
        runs-on: ubuntu-latest
        steps:
            -   uses: hmarr/debug-action@v2

            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Build and save Docker images
                run: |
                    docker build --tag $DOCKER_IMAGE_FRONT --file build/docker/front.build.dockerfile .
                    docker save $DOCKER_IMAGE_FRONT > $DOCKER_IMAGE_FRONT.tar

            -   name: Upload artifacts
                uses: actions/upload-artifact@v3
                with:
                    name: my-artifacts
                    path: ${{env.DOCKER_IMAGE_FRONT}}.tar

    build-back:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Build and save Docker images
                run: |
                    docker build --tag $DOCKER_IMAGE_BACK --file build/docker/back.build.dockerfile .
                    docker save $DOCKER_IMAGE_BACK > $DOCKER_IMAGE_BACK.tar

            -   name: Upload artifacts
                uses: actions/upload-artifact@v3
                with:
                    name: my-artifacts
                    path: ${{env.DOCKER_IMAGE_BACK}}.tar

    deploy:
        needs: [ build-front, build-back ]
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Download artifacts
                uses: actions/download-artifact@v3
                with:
                    name: my-artifacts
                    path: artifacts

            -   name: Copy docker-compose.dev.yml to server
                uses: appleboy/scp-action@master
                with:
                    host: ${{ secrets.VPS_HOST }}
                    username: ${{ secrets.VPS_USERNAME }}
                    password: ${{ secrets.VPS_PASSWORD }}
                    port: ${{ secrets.VPS_PORT }}
                    source: ./build/docker-compose.prod.yml
                    target: /home/${{ secrets.VPS_USERNAME }}/app/


            -   name: Copy back artifact to server
                uses: appleboy/scp-action@master
                with:
                    host: ${{ secrets.VPS_HOST }}
                    username: ${{ secrets.VPS_USERNAME }}
                    password: ${{ secrets.VPS_PASSWORD }}
                    port: ${{ secrets.VPS_PORT }}
                    source: ./artifacts/${{env.DOCKER_IMAGE_BACK}}.tar
                    target: /home/${{ secrets.VPS_USERNAME }}/app/
                    timeout: 300s

            -   name: Copy front artifact to server
                uses: appleboy/scp-action@master
                with:
                    host: ${{ secrets.VPS_HOST }}
                    username: ${{ secrets.VPS_USERNAME }}
                    password: ${{ secrets.VPS_PASSWORD }}
                    port: ${{ secrets.VPS_PORT }}
                    source: ./artifacts/${{env.DOCKER_IMAGE_FRONT}}.tar
                    target: /home/${{ secrets.VPS_USERNAME }}/app/
                    timeout: 300s

            -   name: Compile and deploy
                uses: appleboy/ssh-action@master
                with:
                    host: ${{ secrets.VPS_HOST }}
                    username: ${{ secrets.VPS_USERNAME }}
                    password: ${{ secrets.VPS_PASSWORD }}
                    timeout: 300s
                    script: |
                        cd /home/${{ secrets.VPS_USERNAME }}/app
                        docker load -i artifacts/${{ env.DOCKER_IMAGE_FRONT }}.tar
                        docker load -i artifacts/${{ env.DOCKER_IMAGE_BACK }}.tar
                        docker compose -f build/docker-compose.prod.yml up --force-recreate
                env:
                    DOCKER_IMAGE_BACK: ${{ env.DOCKER_IMAGE_BACK }}
                    DOCKER_IMAGE_FRONT: ${{ env.DOCKER_IMAGE_FRONT }}
